// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: core_config_data.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConfig = `-- name: CreateConfig :one
INSERT
INTO core_config_data (path, value)
VALUES ($1, $2)
RETURNING config_id, path, value, created_at, updated_at
`

type CreateConfigParams struct {
	Path  string      `json:"path"`
	Value pgtype.Text `json:"value"`
}

func (q *Queries) CreateConfig(ctx context.Context, arg *CreateConfigParams) (CoreConfigDatum, error) {
	row := q.db.QueryRow(ctx, createConfig, arg.Path, arg.Value)
	var i CoreConfigDatum
	err := row.Scan(
		&i.ConfigID,
		&i.Path,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConfig = `-- name: DeleteConfig :one
DELETE
FROM core_config_data
Where path = $1
RETURNING config_id, path, value, created_at, updated_at
`

func (q *Queries) DeleteConfig(ctx context.Context, path string) (CoreConfigDatum, error) {
	row := q.db.QueryRow(ctx, deleteConfig, path)
	var i CoreConfigDatum
	err := row.Scan(
		&i.ConfigID,
		&i.Path,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConfig = `-- name: GetConfig :one
SELECT config_id, path, value, created_at, updated_at
FROM core_config_data
Where path = $1
`

func (q *Queries) GetConfig(ctx context.Context, path string) (CoreConfigDatum, error) {
	row := q.db.QueryRow(ctx, getConfig, path)
	var i CoreConfigDatum
	err := row.Scan(
		&i.ConfigID,
		&i.Path,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConfig = `-- name: UpdateConfig :one
UPDATE core_config_data
SET value = $2
Where path = $1
RETURNING config_id, path, value, created_at, updated_at
`

type UpdateConfigParams struct {
	Path  string      `json:"path"`
	Value pgtype.Text `json:"value"`
}

func (q *Queries) UpdateConfig(ctx context.Context, arg *UpdateConfigParams) (CoreConfigDatum, error) {
	row := q.db.QueryRow(ctx, updateConfig, arg.Path, arg.Value)
	var i CoreConfigDatum
	err := row.Scan(
		&i.ConfigID,
		&i.Path,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
