// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CoreConfigDatum struct {
	ConfigID  int64       `json:"config_id"`
	Path      string      `json:"path"`
	Value     pgtype.Text `json:"value"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}
