// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateConfig(ctx context.Context, arg *CreateConfigParams) (CoreConfigDatum, error)
	DeleteConfig(ctx context.Context, path string) (CoreConfigDatum, error)
	GetConfig(ctx context.Context, path string) (CoreConfigDatum, error)
	UpdateConfig(ctx context.Context, arg *UpdateConfigParams) (CoreConfigDatum, error)
}

var _ Querier = (*Queries)(nil)
